apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres-secret
type: Opaque
data:
  db-name: Q2FyZ29Vc2VyRGF0YWJhc2U=
  db-user: cm9vdA==
  db-password: bXRobi50cmttbjEyMw==
  pg-email: bXRobnRya21ubjExNzFAZ21haWwuY29t
  pg-password: bXRobi50cmttbjEyMw==