version: "1"

services:
  mailing_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    networks:
      - authentication_postgres

networks:
  authentication_postgres :
    external: true
