version: "1"

services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - authentication_postgres
    depends_on:
      - mqapplication

  mqapplication:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - authentication_postgres

networks:
  authentication_postgres :
    external: true