services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mthn.trkmn123
      POSTGRES_DB: CargoUserDatabase
    networks:
      - postgres

    ports:
      - 5432:5432
    #restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mthntrkmnn1171@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mthn.trkmn123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    restart: always
    networks:
      - postgres

  your-java-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - postgres


networks:
  postgres:
    driver: bridge